ShoesShopOnline/Models/SanPham.cs
namespace ShoesShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("SanPham")]
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            AnhMoTas = new HashSet<AnhMoTa>();
        }

        [Key]
        [StringLength(10)]
        public string MaSP { get; set; }

        [Required]
        [StringLength(200)]
        public string TenSP { get; set; }

        [StringLength(20)]
        public string MaDM { get; set; }

        public int? MaKM { get; set; }

        [StringLength(500)]
        public string MoTa { get; set; }

        [Column(TypeName = "money")]
        public decimal GiaBan { get; set; }

        public DateTime NgayTao { get; set; }

        public DateTime NgaySua { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnhMoTa> AnhMoTas { get; set; }

        public virtual DanhMucSP DanhMucSP { get; set; }

        public virtual KhuyenMaiSP KhuyenMaiSP { get; set; }
    }
}

ShoesShopOnline/Areas/Admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using PagedList;
using ShoesShopOnline.Models;

namespace ShoesShopOnline.Areas.Admin.Controllers
{
    public class SanPhamsController : BaseController
    {
        private Shoes db = new Shoes();

        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page,string madm, string makm)
        {
            /*var result = (from p in db.SanPhams
                           join a in db.AnhMoTas on p.MaSP equals a.MaSP
                           join kn in db.KhuyenMaiSPs on p.MaKM equals kn.MaKM
                           select new ProductDetail()
                           {
                               MaSP = p.MaSP,
                               TenSP = p.TenSP,
                               MaDM = p.DanhMucSP.TenDanhMuc,
                               Anh = a.HinhAnh,
                               MoTa = p.MoTa,
                               GiaBan = p.GiaBan,
                               NgaySua = p.NgaySua,
                               MaKH = p.MaKM,
                           }).ToList();*/
            var result = db.SanPhams.Join(db.AnhMoTas, p => p.MaSP, a => a.MaSP, (p, a) => new ProductDetail
            {
                MaSP = p.MaSP,
                TenSP = p.TenSP,
                MaDM = p.DanhMucSP.TenDanhMuc,
                Anh = a.HinhAnh,
                MoTa = p.MoTa,
                GiaBan = p.GiaBan,
                NgaySua = p.NgaySua,
                MaKH = p.MaKM,

            }).ToList();
            var productDetails = new List<ProductDetail>();
            foreach (var item in result)
            {
                int dem = 0;
                foreach (var t in productDetails)
                {
                    if (item.MaSP.Equals(t.MaSP))
                        dem++;
                }
                if (dem == 0)
                    productDetails.Add(item);
            }
            productDetails = productDetails.OrderByDescending(p => p.NgaySua).ToList();
            ViewBag.CurrentSort = sortOrder;
            ViewBag.SapTheoTen = String.IsNullOrEmpty(sortOrder) ? "ten_desc" : "";
            ViewBag.SapTheoGia = sortOrder == "gia" ? "gia_desc" : "gia";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                productDetails = productDetails.Where(p => p.TenSP.ToLower().Contains(searchString.ToLower())).ToList();
            }
            switch (sortOrder)
            {
                case "ten_desc":
                    productDetails = productDetails.OrderByDescending(p => p.TenSP).ToList();
                    break;
                case "gia":
                    productDetails = productDetails.OrderBy(p => p.GiaBan).ToList();
                    break;
                case "gia_desc":
                    productDetails = productDetails.OrderByDescending(p => p.GiaBan).ToList();
                    break;
                default:
                    productDetails = productDetails.OrderByDescending(p => p.NgaySua).ToList();
                    break;
            }
            ViewBag.MaDM = new SelectList(db.DanhMucSPs, "MaDM", "TenDanhmuc");
            ViewBag.MaKM = new SelectList(db.KhuyenMaiSPs, "MaKM", "MaKM");
            if (madm != null && makm!=null)
            {
                var sp = db.SanPhams.Where(x => x.MaDM == madm).ToList();
                foreach (var item in sp)
                {
                    if (item.MaKM == null)
                    {
                        item.MaKM = int.Parse(makm);
                    }
                    item.MaKM =int.Parse( makm);
                    db.SaveChanges();
                }
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(productDetails.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Details(string id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                SanPham sanPham = db.SanPhams.Find(id);
                if (sanPham == null)
                {
                    return HttpNotFound();
                }
                var images = db.AnhMoTas.Where(p => p.MaSP == id).ToList();
                var maAnh = 0;
                string filePath = "";
                if (images != null)
                {
                    foreach (var item in images)
                    {
                        filePath += item.HinhAnh + ";";
                        maAnh = item.MaAnh;
                    }
                }
                filePath = filePath.Substring(0, filePath.Length - 1);
                ViewBag.filePath = filePath;
                var sizes = db.ChiTietSanPhams.Where(p => p.MaAnh == maAnh).ToList();
                string listSize = "";
                if (sizes != null)
                {
                    foreach (var item in sizes)
                    {
                        listSize += item.KichCo + "; ";
                    }
                }
                listSize = listSize.Substring(0, listSize.Length - 2);
                ViewBag.listSize = listSize;
                return View(sanPham);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi !" + ex.Message;
                return View();
            }

        }

        public ActionResult Create()
        {
            ViewBag.MaDM = new SelectList(db.DanhMucSPs, "MaDM", "TenDanhMuc");
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductDetail productDetail, List<HttpPostedFileBase> uploadFile)
        {
            try
            {
                productDetail.Anh = "";
                if (ModelState.IsValid)
                {
                    SanPham sanPham = new SanPham();
                    string maSP = "";
                    var list = db.SanPhams.ToList();
                    var sanpham = list.LastOrDefault();
                    if (sanpham == null)
                    {
                        maSP = "SP001";
                    }
                    else
                    {
                        int index = int.Parse(sanpham.MaSP.Substring(2, 3)) + 1;
                        maSP = "SP" + string.Format(CultureInfo.CreateSpecificCulture("da-DK"), "{0:000}", index);
                    }
                    sanPham.MaSP = maSP;
                    sanPham.TenSP = productDetail.TenSP;
                    sanPham.MaDM = productDetail.MaDM;
                    sanPham.MoTa = productDetail.MoTa;
                    sanPham.GiaBan = productDetail.GiaBan;
                    sanPham.NgayTao = DateTime.Now;
                    sanPham.NgaySua = DateTime.Now;
                    sanpham.MaKM = productDetail.MaKH;
                    db.SanPhams.Add(sanPham);
                    db.SaveChanges();
                    //Add Anh
                    string[] sizes = productDetail.Size.Split(';');
                    foreach (var item in uploadFile)
                    {
                        AnhMoTa anhMoTa = new AnhMoTa();
                        string FileName = item.FileName;
                        string filePath = Path.Combine(HttpContext.Server.MapPath("/wwwroot/Images"),
                                                       Path.GetFileName(item.FileName));
                        item.SaveAs(filePath);
                        anhMoTa.HinhAnh = FileName;
                        anhMoTa.MaSP = maSP;
                        db.AnhMoTas.Add(anhMoTa);
                        db.SaveChanges();
                        //Add san pham chi tiet
                        for (int j = 0; j < sizes.Length; j++)
                        {
                            ChiTietSanPham chiTietSanPham = new ChiTietSanPham();
                            chiTietSanPham.MaAnh = anhMoTa.MaAnh;
                            chiTietSanPham.KichCo = int.Parse(sizes[j]);
                            db.ChiTietSanPhams.Add(chiTietSanPham);
                            db.SaveChanges();
                        }
                    }

                    return RedirectToAction("Index");
                }
                ViewBag.MaDM = new SelectList(db.DanhMucSPs, "MaDM", "TenDanhMuc", productDetail.MaDM);
                return View(productDetail);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "Lỗi nhập dữ liệu !" + ex.Message;
                ViewBag.MaDM = new SelectList(db.DanhMucSPs, "MaDM", "TenDanhMuc", productDetail.MaDM);
                return View(productDetail);

            }

        }

        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            int maAnh = 0;
            var images = db.AnhMoTas.Where(p => p.MaSP == id).ToList();
            string filePath = "";
            if (images != null)
            {
                foreach (var item in images)
                {
                    maAnh = item.MaAnh;
                    filePath += item.HinhAnh + ";";
                }
            }
            filePath = filePath.Substring(0, filePath.Length - 1);

ShoesShopOnline/Areas/Admin/Views/SanPhams/Create.cshtml
@model ShoesShopOnline.Models.ProductDetail

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
    <style>
        .row {
            width: 25%;
            float: left;
            padding: 10px 20px;
        }

        a[class="btnAddNew"] {
            color: white;
            background-color: navy;
            padding: 10px;
            border: none;
            width: 100px;
            border-radius: 5px;
            text-align: center;
            margin-top: 20px;
            height: 50px;
            line-height: 50px;
        }

        a[class="btnRemove"] {
            height: 30px;
            line-height: 30px;
            color: white;
            background-color: red;          
            border: none;
            width: 60px;
            border-radius: 5px;
            margin: 15px 10px;
            text-align: center;
        }

        img {
            padding: 10px 20px;
        }
    </style>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var max_fields = 10; //maximum input boxes allowed
            var wrapper = $(".myinput"); //Fields wrapper
            var add_button = $(".btnAddNew"); //Add button ID

            var x = 0; //initlal text box count
            $(add_button).click(function (e) { //on add input button click
                e.preventDefault();
                if (x < max_fields) { //max input box allowed
                    x++; //text box increment
                    $(wrapper).append('<div class="row"> <img class="img-rounded output" alt="Ảnh" width="100" height="230" src="~/wwwroot/Images/h0.png" />  <input type="file" name="uploadFile[' + x + ']" onchange="loadFile(event)"/><a href="#" class="btnRemove">Xóa</a></div>'); //add input box

                }
            });

            $(wrapper).on("click", ".btnRemove", function (e) { //user click on remove text
                e.preventDefault(); $(this).parent('div').remove(); x--;
            })
        });
    </script>
    @section Ckeditor{
        <script>
            CKEDITOR.replace("MoTa");
        </script>
    }
</head>
<body>
    @if (ViewBag.Error != null)
    {
        <br />
        <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
    }
@using (Html.BeginForm("Create", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Thêm sản phẩm mới</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaDM, "MaDM", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class=" form-group">
        <label>Ảnh sản phẩm </label><br />
        <a class="btnAddNew ThemMoi" href="#">Thêm Ảnh</a>
        <br />
        <div id="myinput" class="myinput">
            <div class="row">
                <img class="img-rounded output" alt="Ảnh" width="100" height="230" src="~/wwwroot/Images/h0.png" />
                <input type="file" name="uploadFile[0]" required onchange="loadFile(event)" /><br />
            </div>
        </div>
        <br />
    </div>
    <div class="form-group" style="clear:both">
        @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control", rows = 50 } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        Mã khuyến mại
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
        </div>
    </div>    
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <hr />
            <input class="btn ThemMoi" style="margin-right:20px"type="submit" value="Thêm" />
            <a class="btn ThemMoi" href="~/Admin/SanPhams/Index">Hủy</a>
        </div>
    </div>
</div>
}

    <script>
        var loadFile = function (event) {
            var images = document.getElementsByClassName('output');
            var image = images[images.length - 1];
            image.src = URL.createObjectURL(event.target.files[0]);

        }
    </script>

</body>
</html>

ShoesShopOnline/Areas/Admin/Views/SanPhams/Details.cshtml
@model ShoesShopOnline.Models.SanPham

@{
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN");
    string[] images = ViewBag.filePath.Split(';');
    string image = "";
    for (int i = 0; i < images.Length; i++)
    {
        image += "<img class=\"rounded\" alt=\"Ảnh\" style=\"margin: 20px\" width=\"150\" height=\"150\" src=\"/wwwroot/Images/" + images[i] + "\">";
    }
}

<div>
    <h4>@Model.TenSP</h4>
    <hr />
    <div>
        <label for="TenDM">Danh mục :</label>
        <span>@Model.DanhMucSP.TenDanhMuc</span>
    </div>
    <div>
        @Html.Raw(System.Web.HttpUtility.HtmlDecode(image))
    </div>
    <div>
        <label for="MoTa">Mô tả :</label>
        @Html.Raw(System.Web.HttpUtility.HtmlDecode(@Model.MoTa))
    </div>
    <div>
        <label for="GiaBan">Giá bán :</label>
        <span>@string.Format(info, "{0:c0}", Model.GiaBan)</span>
    </div>
    <div>
        <label for="GiaBan">Các size sẵn có :</label>
        <span>@ViewBag.listSize</span>
    </div>
    <div>
        <label for="NgayTao">Ngày tạo :</label>
        <span>@Model.NgayTao</span>
    </div>
    <div>
        <label for="NgaySua">Ngày sửa :</label>
        <span>@Model.NgaySua</span>
    </div>
    <div>
        <label for="MaKH">Mã khuyến mại :</label>
        <span>@Model.MaKM</span>
    </div>
</div>
    <p>
        <hr />
        <a class="btn ThemMoi" style="margin-right:20px" href="~/Admin/SanPhams/Edit/@Model.MaSP">Sửa sản phẩm</a>
        <a class="btn ThemMoi" href="~/Admin/SanPhams/Index">Trở về</a>
    </p>

ShoesShopOnline/Areas/Admin/Views/SanPhams/Edit.cshtml
@model ShoesShopOnline.Models.ProductDetail

@{
    string name = ViewBag.filePath;
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
    string image = "";
    if (ViewBag.filePath != null) {
        string[] images = ViewBag.filePath.Split(';');
        for (int i = 0; i < images.Length; i++)
        {
            image += "<div class=\"row\"><img class=\"img-rounded output\" name=\"uploadFile[" + i + "]\" alt=\"Ảnh\" width=\"100\" height=\"230\" src=\"/wwwroot/Images/" + images[i] + "\"><br/><a href=\"#\" class=\"btnRemove\">Xóa</a></div>";
        }
    }
    
    else
    {
        image = "";
    }

}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <style>
        .row {
            width: 25%;
            float: left;
            padding: 10px 20px;
        }

        a[class="btnAddNew"] {
            color: white;
            background-color: navy;
            padding: 10px;
            border: none;
            width: 300px;
            border-radius: 5px;
            text-align: center;
            margin-top: 20px;
            height: 50px;
            line-height: 50px;
        }

        a[class="btnRemove"] {
            height: 30px;
            line-height: 30px;
            color: white;
            background-color: red;
            border: none;
            width: 60px;
            border-radius: 5px;
            margin: 15px 10px;
            text-align: center;
        }

        a[class="btnRemoveNew"] {
            height: 30px;
            line-height: 30px;
            color: white;
            background-color: red;
            border: none;
            width: 60px;
            border-radius: 5px;
            margin: 15px 10px;
            text-align: center;
        }

        img {
            padding: 10px 20px;
        }
    </style>
    <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var max_fields = 10; //maximum input boxes allowed
            var wrapper = $(".myinput"); //Fields wrapper
            var add_button = $(".btnAddNew"); //Add button ID


            var t = 0;
            var indexmoi = 0;
            var indexcu = 100;
            var x = 0; //initlal text box count
            $(add_button).click(function (e) { //on add input button click
                e.preventDefault();
                if (x < max_fields) { //max input box allowed
                    x++; //text box increment
                    $(wrapper).append('<div class="row"> <img class="img-rounded output" alt="Ảnh" width="100" height="230" src="~/wwwroot/Images/h0.png" />  <input type="file" name="uploadFile" onchange="loadFile(event)"/><a href="#" class="btnRemoveNew">Xóa</a></div>'); //add input box

                }
            });

            $(wrapper).on("click", ".btnRemove", function (e) { //user click on remove text
                value = $(this).parent().parent().prev().children(':first-child').val();
                if (value != "") {
                    name = $(this).prev().prev().attr("name");
                    indexmoi = name.match(/[0-9]+/)[0];
                    if (indexmoi > indexcu) {
                        t++;
                        indexmoi = indexmoi - t;
                    }
                    indexcu = indexmoi;


                    var list = value.split(';');
                    list.splice(indexmoi, 1);
                    var result = "";
                    for (let i = 0; i < list.length; i++) {
                        result += list[i] + ";";
                    }
                    result = result.substring(0, result.length - 1);
                    $(this).parent().parent().prev().children(':first-child').val(result);
                }

                e.preventDefault(); $(this).parent('div').remove(); x--;

            })
            //Remove Image New
            $(wrapper).on("click", ".btnRemoveNew", function (e) { //user click on remove text
                e.preventDefault(); $(this).parent('div').remove(); x--;
            })
        });
    </script>
    @section Ckeditor{
        <script>
            CKEDITOR.replace("MoTa");
        </script>
    }
</head>
<body>
    @if (ViewBag.Error != null)
    {
        <br />
        <div class="alert alert-danger" role="alert">@ViewBag.Error</div>
    }
    @using (Html.BeginForm("Edit", "SanPhams", FormMethod.Post, new { enctype = "multipart/form-data", MaSP=Model.MaSP }))
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Cập nhật thông tin sản phẩm</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.TenSP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TenSP, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TenSP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MaDM, "MaDM", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("MaDM", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.MaDM, "", new { @class = "text-danger" })
        </div>
    </div>r
    <div class=" form-group">
        <label>Ảnh sản phẩm </label><br />
        <a class="btnAddNew ThemMoi" href="#">Thêm Ảnh</a>
        <br />
        <div class="col-md-10">
            @Html.EditorFor(model => model.Anh, new { htmlAttributes = new { @class = "form-control", style = "visibility:hidden;" } })
            @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
        </div>
        <div id="myinput" class="myinput">
            @Html.Raw(System.Web.HttpUtility.HtmlDecode(image))
        </div>
        <br />
    </div>
    <div class="form-group" style="clear:both">
        @Html.LabelFor(model => model.Size, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Size, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Size, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MoTa, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control", rows = 50 } })
            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GiaBan, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.GiaBan, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.GiaBan, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        Mã khuyến mại
        <div class="col-md-10">
            @Html.EditorFor(model => model.MaKH, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MaKH, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <hr />
            <input class="btn ThemMoi" style="margin-right:20px" type="submit" value="Lưu" />
            <a class="btn ThemMoi" href="~/Admin/SanPhams/Index">Hủy</a>
        </div>
    </div>
</div>
    }

    <script>
        var loadFile = function (event) {
            var images = document.getElementsByClassName('output');
            var image = images[images.length - 1];
            image.src = URL.createObjectURL(event.target.files[0]);
        }
    </script>

</body>
</html>